// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/popup-colors/OptionA.tsx": () => import("../components/mockups/popup-colors/OptionA.tsx"),
  "./components/mockups/popup-colors/OptionB.tsx": () => import("../components/mockups/popup-colors/OptionB.tsx"),
  "./components/mockups/popup-colors/OptionC.tsx": () => import("../components/mockups/popup-colors/OptionC.tsx"),
  "./components/mockups/popup-colors/OptionD.tsx": () => import("../components/mockups/popup-colors/OptionD.tsx")
};
