// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sidebar-layouts/Compact.tsx": () => import("../components/mockups/sidebar-layouts/Compact.tsx"),
  "./components/mockups/sidebar-layouts/Minimal.tsx": () => import("../components/mockups/sidebar-layouts/Minimal.tsx"),
  "./components/mockups/sidebar-layouts/Tabbed.tsx": () => import("../components/mockups/sidebar-layouts/Tabbed.tsx")
};
