// Magic Card - Dedicated print page for Chrome Extension
// This avoids CSP issues with inline scripts

document.addEventListener('DOMContentLoaded', async () => {
  const cardContent = document.getElementById('cardContent');
  const saveBtn = document.getElementById('saveBtn');
  const printBtn = document.getElementById('printBtn');
  const copyBtn = document.getElementById('copyBtn');
  
  // Get content from storage
  try {
    const result = await chrome.storage.local.get('magicCardContent');
    if (result.magicCardContent) {
      cardContent.innerHTML = result.magicCardContent;
      // Clear it after reading
      await chrome.storage.local.remove('magicCardContent');
    } else {
      cardContent.innerHTML = '<p>No content available. Please try again from the AI chat.</p>';
    }
  } catch (err) {
    console.error('Failed to load magic card content:', err);
    cardContent.innerHTML = '<p>Failed to load content. Please try again.</p>';
  }
  
  // Save PDF button - Direct download using jsPDF
  saveBtn.addEventListener('click', () => {
    if (!window.jspdf || !window.jspdf.jsPDF) {
      alert('PDF library failed to load. Please use Print instead.');
      return;
    }
    
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });
    
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - (margin * 2);
    let yPosition = margin;
    
    // Title
    doc.setFontSize(16);
    doc.setTextColor(0, 82, 204);
    doc.text('SnapToAI Magic Card', margin, yPosition);
    yPosition += 8;
    
    // Date
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(new Date().toLocaleString(), margin, yPosition);
    yPosition += 6;
    
    // Line separator
    doc.setDrawColor(0, 217, 255);
    doc.setLineWidth(0.5);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;
    
    // Get plain text content
    const text = cardContent.innerText.trim();
    
    // Add content with word wrapping
    doc.setFontSize(11);
    doc.setTextColor(51, 51, 51);
    
    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach(line => {
      if (yPosition > pageHeight - 20) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += 6;
    });
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by SnapToAI', margin, pageHeight - 10);
    
    // Generate filename and download
    const timestamp = new Date().toISOString().slice(0, 10);
    doc.save(`SnapToAI-MagicCard-${timestamp}.pdf`);
    
    // Visual feedback
    const originalText = saveBtn.textContent;
    saveBtn.textContent = 'Saved!';
    saveBtn.style.background = 'linear-gradient(135deg, #10b981 0%, #059669 100%)';
    setTimeout(() => {
      saveBtn.textContent = originalText;
      saveBtn.style.background = '';
    }, 2000);
  });
  
  // Print button
  printBtn.addEventListener('click', () => {
    window.print();
  });
  
  // Copy button
  copyBtn.addEventListener('click', async () => {
    try {
      // Copy as rich HTML
      const htmlContent = cardContent.innerHTML;
      const textContent = cardContent.innerText;
      
      // Try to copy both HTML and plain text
      const blob = new Blob([htmlContent], { type: 'text/html' });
      const textBlob = new Blob([textContent], { type: 'text/plain' });
      
      await navigator.clipboard.write([
        new ClipboardItem({
          'text/html': blob,
          'text/plain': textBlob
        })
      ]);
      
      // Visual feedback
      const originalText = copyBtn.textContent;
      copyBtn.textContent = 'Copied!';
      copyBtn.style.background = 'linear-gradient(135deg, #10b981 0%, #059669 100%)';
      setTimeout(() => {
        copyBtn.textContent = originalText;
        copyBtn.style.background = '';
      }, 2000);
    } catch (err) {
      console.error('Copy failed:', err);
      // Fallback to plain text
      try {
        await navigator.clipboard.writeText(cardContent.innerText);
        copyBtn.textContent = 'Copied (text only)';
        setTimeout(() => {
          copyBtn.textContent = 'Copy to Clipboard';
        }, 2000);
      } catch (e) {
        copyBtn.textContent = 'Copy failed';
        setTimeout(() => {
          copyBtn.textContent = 'Copy to Clipboard';
        }, 2000);
      }
    }
  });
});
